# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
#
require 'rubygems'
require 'bundler/setup'
require 'rails/railtie'
require 'pry-nav'
require 'action_view'
require 'active_support'
require 'rspec/collection_matchers'
require 'grouped_time_zones'

include ActionView::Helpers

RSpec.configure do |config|
  config.expect_with :rspec do |c|
    # FIXME: enable should until specs are updated
    c.syntax = [:should, :expect]
  end
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end
